name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        run: tar -czf casecobra-app.tar.gz .next package.json next.config.js

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: casecobra-app
          path: casecobra-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: casecobra-app
          path: casecobra-app.tar.gz

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_VPS1 }}

      - name: Deploy to VPS
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_VPS1 }}
        run: |
          echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
          scp -o StrictHostKeyChecking=no casecobra-app.tar.gz user@vps_ip_address:/home/user
          ssh -o StrictHostKeyChecking=no user@vps_ip_address << 'EOF'
            cd /home/user
            tar -xzf casecobra-app.tar.gz -C /path/to/your/application
            cd /path/to/your/application
            npm install --production
            pm2 restart casecobra || pm2 start npm --name "casecobra" -- start
          EOF
